### ISSUE TITLE
No working

### ISSUE THREAD

**Issue by maciejmyslinski** [LingyuCoder/hexo-generator-autoprefixer#1]
``` bash
FATAL callback is not a function.
```

Changes in configuration do not fix it.

```
hexo: 3.2.0
hexo-cli: 1.0.1
os: Darwin 15.3.0 darwin x64
http_parser: 2.6.0
node: 5.3.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e
```

**Comment by LingyuCoder** [comment]
Sorry, this hexo plugin only works on hexo 2.x

2016-03-15 23:55 GMT+08:00 Maciej notifications@github.com:

**Comment by maciejmyslinski** [comment]
Thank you! Since 2.x is not current version of Hexo you should write about that fact in README.
Best regards,
Maciej

**Comment by LingyuCoder** [comment]
Thank you so much, I have added this in README
